### ISSUE TITLE
[Feat] Page "Sur les pas des artistes"

### ISSUE THREAD

**Issue by Arzoter** [thomasflorentin/amisbm#28]
- Contenus et styles à intégrer

**Comment by thom4s** [comment]
y'a quoi à faire ici ?

**Comment by Arzoter** [comment]
Pour l'instant, on a pas les contenus (il faut voir avec Daniel) mais il faut s'occuper de voir si tout s'affiche bien

**Comment by thom4s** [comment]
on en a discuter avec Daniel. rien à faire là dessus de notre côté.
