### ISSUE TITLE
[FONT] Cimetière - Intro color & size

### ISSUE THREAD

**Issue by Arzoter** [thomasflorentin/amisbm#29]
- Mettre le paragraphe d'intro en bleu
- - Augmenter légèrement la taille

**Comment by Arzoter** [comment]
UPDATE : La page utilise le template de base des pages, il faut trouver un moyen simple de permettre sa customisation via gutemberg

* Solution 1 : On créé un template spécial
* Solution 2 : On forme les utilisateurs à l'utilisation de shortcodes / ajout de classes CSS supplémentaires

**Comment by thom4s** [comment]
Pour moi cette page n'a pas de gabarit particulier. C'est une page par défaut. 
L'introduction est comme sur toutes les pages...
