### ISSUE TITLE
[CSS] typo copy

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#37]
- https://abm.stagingserver.fr/publication/dans-lintimite-de-la-communaute/
- font-size: 1.8rem  sur les p

**Comment by Arzoter** [comment]
UPDATE : les modifs ont été intégrées mais ça rend très gros (voir PJ), on réduit la taille ?
![image](https://user-images.githubusercontent.com/71469752/213151159-5628c35b-4f5a-4a85-a563-d67e09647e5c.png)

**Comment by thom4s** [comment]
non non ça me parait bien.

**Comment by thom4s** [comment]
par contre, je ne vois pas les modifications dans le git... ?

**Comment by Arzoter** [comment]
J'avais pas encore push ces modifs là, ça devrait être bon maintenant.
