### ISSUE TITLE
[MOBILE] Affiner la version mobile

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#39]
Sous 800px en gros : 
- tous contenus sur 1 colonnes
- menu Burger
- réduire un peu les typos
- tailles hero (accueil et ailleurs)

**Comment by Arzoter** [comment]
UPDATE : Ajout des styles responsive & du script JS pour le menu burger du header.
J'attend de finir le système de grille pour m'attaquer au reste, sinon je ferai le travail deux fois.

**Comment by thom4s** [comment]
Ok bien lu. 

- baisser certaines tailles de typos ici et là. Fais TOUTES les pages et réduit pour les titres rentrent dans les pages.
- prends une largeur d'écran de 400px pour référence
- fais aussi attention aux Hero : leur hauteur (height) est relative à la hauteur de l'écran... DONC possible problème de place. 
- mieux vaut laisser les Hero libre en hauteur en mobile. Tu ajoutes juste des paddings pour le style.
