### ISSUE TITLE
[PUBLICATIONS] Dynamiser bouton "Commande"

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#40]
- https://abm.stagingserver.fr/publication/eugene-ciceri/#
- en bas de la page
- dynamiser le bouton, qu'on puisse éditer le lien de la page en BO.

**Comment by Arzoter** [comment]
Je suis pas sur de comprendre ce que "dynamiser le bouton, qu'on puisse éditer le lien de la page en BO" veut dire. On veut :
* Pouvoir rediriger vers une URL précisée dans le BO au clic du bouton ?
* Faire passer les arguments du post dans l'URL pour les récupérer sur la future page de contact/commande ?

**Comment by thom4s** [comment]
non : 
- dans chaque page publication, on a un bouton en bas : COMMANDER
- il faudrait qu'il y ait un lien sur ce bouton
- on peut mettre le lien en statique comme des barbares, genre href="/commande"
- mais si la page commande change un jour, il faut retoucher le code
- ... donc il faut créer un champ ACF dans les Options peut être et définir une page Commande que l'on pourrait récupérer sur le site genre get_field('commande_url', options)
- et donc utiliser ce champs entre autrses sur les pages de publications....
