### ISSUE TITLE
[SEARCH] Ajouter la valeur du texte recherché

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#41]
- https://abm.stagingserver.fr/?s=auguste
- ajouter à côté de "Recherche" le terme recherché
- https://developer.wordpress.org/reference/functions/get_search_query/

**Comment by Arzoter** [comment]
![image](https://user-images.githubusercontent.com/71469752/213156552-2be609f2-0fb8-4de0-aebf-7f845110bc2e.png)

**Comment by thom4s** [comment]
ça ira comme ça pour le moment. on verra plus tard;
