### ISSUE TITLE
[Gutemberg] Alignements textes

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#55]
Voir si on peut aligner verticalement un texte dans une colonne
https://abm.stagingserver.fr/nouveau-bulletin/

**Comment by thom4s** [comment]
Comment tu as fait ?

**Comment by Arzoter** [comment]
Y'a une option dans Gutemberg :
![image](https://user-images.githubusercontent.com/71469752/216067477-503ab839-70b1-497a-90e1-9ef7475635ba.png)
