### ISSUE TITLE
[PUBLICATIONS] Marges

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#59]
- ajouter plus de marge sous bloc publication

**Comment by Arzoter** [comment]
![image](https://user-images.githubusercontent.com/71469752/215791933-a1f423b9-441c-46a4-aafe-f9fc2e9a9e89.png)
Tu veux que j'ajoute des marges en dessous de ces blocs là, c'est ça ?

**Comment by thom4s** [comment]
Oui oui.
