### ISSUE TITLE
[Header] Logo + Form

### ISSUE THREAD

**Issue by thom4s** [thomasflorentin/amisbm#63]
Une demande de Daniel, pour gagner un peu de hauteur... : 
- On vire le logo du Header
- On le met dans le footer avec les autres logos
- On met le Formulaire collé à gauche
- et le menu reste à droite, sur la même "ligne" que le formulaire

et vérifier le reponsive.

**Comment by Arzoter** [comment]
Je m'y met, faudra juste penser à ajouter un lien vers l'accueil dans le menu du header du coup, jusqu'à maintenant, y'avait que le logo qui nous servait de lien vers l'accueil.

**Comment by Arzoter** [comment]
Résultat :
* Header "déplié" (même si c'est beaucoup moins visible qu'avant)
![image](https://user-images.githubusercontent.com/71469752/217787937-7f7ad4f8-355a-4bd0-8361-3fc1add65217.png)

* Header "plié"
![image](https://user-images.githubusercontent.com/71469752/217788098-4fd30602-21b2-427a-b612-10b37e82cba1.png)

* Footer
![image](https://user-images.githubusercontent.com/71469752/217788198-12f47c1c-7a21-4a87-b26c-46ca8e21ee57.png)
